### **addition**

In [5]:
import numpy as np

a=np.array([10,20,30])
b=np.array([1,2,3])
a+b

array([11, 22, 33])

**subtraction**

In [6]:
import numpy as np
a=np.array([40,50,60])
b=np.array([16,17,20])
a-b

array([24, 33, 40])

**multipliction**

In [7]:
import numpy as np
a=np.array([50,60,70])
b=np.array([10,20,30])
a*b

array([ 500, 1200, 2100])